milmove-app/Dockerfile
Releases haven't been made for a while, so this update was bad.
=> Fix go-bindata

Dockerfile
Updating based on https://github.com/aws/aws-cli/issues/5013
=> Version the awscli to v2.0.1

milmove-infra/Dockerfile
=> Upgrade terraform 0.12.22

.dependabot/config.yml
We want dependabot checking all these.
=> Ensure dependabot is checking all the docker files

Dockerfile
=> Update circleci version to 0.1.6772+67c7d52

build, milmove-app/Dockerfile, milmove-orders/Dockerfile
Update version of chamber. Also ensure cache busting is correct.
=> Update chamber 2.8.0

Dockerfile, milmove-app/Dockerfile, milmove-orders/Dockerfile
Turns out using this in Infra for development would be super nice.
=> Move chamber to the docker base image so infra can also use it.

Dockerfile
=> Update awscli to 2.0.4

Dockerfile
=> Upgrade aws cli to 2.0.5

milmove-infra/Dockerfile
=> Update terraform to 0.12.24

milmove-infra/Dockerfile
=> Update terraform docs 0.9.1

.circleci/config.yml, Makefile
A `Makefile` just makes things easier.
=> Cg add makefile

Dockerfile
=> Upgrade awscli to 2.0.7

Dockerfile
=> Upgrade awscli to 2.0.9

Dockerfile
Two tools have been updated, AWS CLI and CircleCI CLI.
=> aws 2.0.10 circleci 7179

Dockerfile, requirements.txt
Some updates that need to be captured.
for clarity).
=> Update CircleCI, AWS, and pre-commit CLI tools

milmove-infra/Dockerfile
Updating terraform 
for clarity).
=> Update terraform version to 0.12.26

Dockerfile, README.md, requirements.txt
=> Updating things

Dockerfile, milmove-app/Dockerfile
=> a few more missing

Dockerfile, milmove-app/Dockerfile, milmove-orders/Dockerfile
=> Updating to latest

Dockerfile, milmove-app/Dockerfile, milmove-infra/Dockerfile, milmove-orders/Dockerfile, requirements.txt
for clarity).
- [go-bindata](https://github.com/kevinburke/go-bindata/releases)
=> No Ticket | Updates Docker containers to latest'ish

Dockerfile
=> [No Ticket] Updates to latest

Dockerfile, milmove-infra/Dockerfile
=> [No Ticket] Updating things, as usual

.circleci/config.yml, README.md, build, milmove-atlantis/Dockerfile, scripts/find-updates
First attempt at this. Be gentle.
Do we even need this? 🐒
=> Atl🍑antis dockerfile

Dockerfile, milmove-infra/Dockerfile, scripts/brew-upgrade
Trying to fix [this](https://app.circleci.com/pipelines/github/transcom/transcom-infrasec-com/3905/workflows/693d74f7-d1a6-4004-a383-2b4d1e8b00ca/jobs/9143)
for clarity).
=> [No Ticket] Updating things cause things updated and transcom-com-infrasec isn't happy

milmove-atlantis/Dockerfile
=> MB-6582: expose port for ATL🍑antis 

milmove-atlantis/Dockerfile
=> MB-6582: update Atlantis image

milmove-app/Dockerfile
Updates go to 1.17.
for clarity).
=> Upgrades go version to 1.17

milmove-app/Dockerfile
=> Upgrade Go to version 1.17.5

milmove-infra-tf112/Dockerfile
hate that this still doesn't work automatically
=> update tfsec to 1.27.1 - manual

.pre-commit-config.yaml
This PR just updates our pre-commit hooks.  Dependabot doesn't update these, so I just used `pre-commit autoupdate` to check for new ones.
Just make sure pre-commit hooks pass locally and in CI.
Locally you can run `pre-commit run -a` to run all files through the pre-commit hooks.
=> [MB-14473] Update all pre-commit hooks

README.md
Removing the images which were deleted in #270.
=> [ spike ] Updating docs to reflect removing milmove-app-browsers

scripts/check-tls-pair
Adding check tls script from mymove 
for clarity).
=> [MB-15388] add check tls script

Dockerfile
=> Update copy script to docker file

.github/workflows/tfsec.yml
for clarity).
- [cypress](https://www.cypress.io/)
- [ecs-service-logs](https://github.com/trussworks/ecs-service-logs/releases)
- [Google Chrome](https://chromereleases.googleblog.com/)
- …
=> Update tfsec.yml workflow updates
