transcom/circleci-docker

Dockerfile

AWS CLI v2 isn't clear about needing this as a dependency. Adding it here is a fix for broken builds.

Include less, required for AWS CLI v2

---

Dockerfile

Once you've installed `less` it now expect you to hit the `return` key. This disables the problem all together.

Disable need for default pager for awscli v2

---

test

A while ago I tried upgrading a binary and cURL returned an empty file. Instead of checking that the new binary worked I just updated the hash that was returned and moved on. Only that meant the build was broken because it turned out the upstream had stopped doing releases, which is how I got the empty file. This attempts to catch that kind of mistake by using the various ways of getting version information from the installed software. The idea is that if the software is correctly installed it ought to return version info, which is a simple and cheap check.

Test that all binaries are installed and work

---

Dockerfile
scripts/README.md
scripts/do-exclusively

This script is pretty integral to doing work on circleci and should be in the base image since almost all builds will need it. It also means I won't need to copy it from the mymove repo to the milmove_orders repo just to use it. 
I've also fixed some script ownership issues I found while investigating this ticket.

Add the do-exclusively script to the images

---

.circleci/config.yml
README.md
build
milmove-app-browsers/Dockerfile
test

Add Dockerfile for creating a milmove-app-browsers image with chrome installed. This is to be used with the Loki tests for Storybook stories.
I used the example from the CircleCI Dockerfile for setting this up.
https://github.com/CircleCI-Public/circleci-dockerfiles/blob/master/node/images/10.19.0-buster/browsers/Dockerfile

Add milmove-app-browsers Dockerfile

---

milmove-app/Dockerfile

We were notified that the go-bindata project released a new version to deal with the fact that the `--version` command returned the wrong version of the code. With this change we'll have the newest code in our docker image. 
TODO: Need to check this version against the application to verify no changes.

Update go-bindata to latest version

---

milmove-infra/Dockerfile

Updating terraform-docs to latest version.
```
cd milmove-infra && docker build .
docker run -it --rm 08c1120605ae terraform-docs --version
terraform-docs version v0.9.0 89b129b linux/amd64 BuildDate: 2020-03-31T20:19:01+0000
```

Update terraform-docs to 0.9.0

---

milmove-app-browsers/Dockerfile

Two things:
- Chrome Stable now requires libgbm1
- Docker linter asks us not to use `sudo` and since we build as root we should be fine.

Chrome stable now requires libgbm1. Remove use of sudo.

---

milmove-app/Dockerfile
milmove-orders/Dockerfile

Upgrade golang to 1.14.2

---

Dockerfile

AWS CLI requires two utilities for help commands and to show output. Instead of continuing to fight this I'm just adding them to our base images.

Install groff and less for AWS CLI

---

.github/PULL_REQUEST_TEMPLATE.md
milmove-infra/Dockerfile
scripts/brew-upgrade
scripts/find-updates
test

Adding [tfsec](https://github.com/liamg/tfsec) tool for pre-commit hook.
for clarity).
- [tfsec](https://github.com/liamg/tfsec/releases)

MB-2473 - Add tfsec to infra container

---

Dockerfile
milmove-infra/Dockerfile
requirements.txt
scripts/find-updates

Updates:
- pre-commit to 2.4.0
- CircleCI to 0.1.7340
- Terraform to 0.12.25

Cg update circleci 0.1.7340 tf 0.12.25 pre commit 2.4.0

---

.github/PULL_REQUEST_TEMPLATE.md
milmove-infra/Dockerfile
test

Adds the tool `find-guardduty-user` into the docker image for use with milmove-infra docker image. This should allow real-time use of the tool inside docker for the infra team.
for clarity).
You can build the images locally and test with
```sh
make build test
```
And if you check the output you'll see:
```sh
$ docker run -it milmove/circleci-docker:milmove-infra find-guardduty-user version
0.0.1
```

Add find-guardduty-user to infra container

---

milmove-infra/Dockerfile

Update terraform version to latest 0.12.28 from 0.12.26
> 0.12.28 (June 25, 2020)
> BUG FIXES:
> 
> build: build the 0.12 version of Terraform with Go 1.12.13, rather than 0.13 Terraform's 1.14.2 (#25386)

update terraform to use 0.12.28

---

milmove-infra/Dockerfile

Update terraform version to latest 0.12.28 from 0.12.26
BUG FIXES:
core: core: Prevent quadratic memory usage with large numbers of instances by not storing the complete resource state in each instance (#25633)
```
docker build --tag milmovetf .
docker run -i --name tftest milmovetf
terraform -v
Terraform v0.12.29
```

update terraform to use 0.12.29

---

milmove-infra/Dockerfile

update tfsec version on docker image
for clarity).
- [tfsec](https://github.com/liamg/tfsec/releases)

MB-4467- update tfsec version on docker image

---

milmove-app/Dockerfile
milmove-orders/Dockerfile

As it says in the title. Upgrades to Go 1.15.2.

Upgrades to Go 1.15.2

---

requirements.txt

https://github.com/transcom/transcom-infrasec-com/pull/1268 that fails in Circle, but doesn't fail locally. Locally, brew upgraded pre-commit to 2.7.1, so this does that.

No Ticket | Upgrade Pre-commit

---

milmove-app/Dockerfile

The mymove app is unable to upgrade its go-openapi dependencies because of an incompatibility introduced in swagger v24.  We can't generate new compatible server structs unless we upgrade the swagger binary from version 21.
[Failing dependency upgrade](https://github.com/transcom/mymove/pull/5029)
[PR to use the new docker image in mymove circleci config and dockerfiles](https://github.com/transcom/mymove/pull/5061)
[go-swagger v24.0 changelog](https://github.com/go-swagger/go-swagger/releases/tag/v0.24.0):

Upgrade go-swagger binary for milmove-app image to version 24

---

milmove-app/Dockerfile
milmove-orders/Dockerfile

Updates go from 1.15.2 to 1.15.5 for minor release that include address some security concerns:
1. go1.15.3 (released 2020/10/14) includes fixes to cgo, the compiler, runtime, the go command, and the bytes, plugin, and testing packages. See the Go 1.15.3 milestone on our issue tracker for details.
1. go1.15.4 (released 2020/11/05) includes fixes to cgo, the compiler, linker, runtime, and the compress/flate, net/http, reflect, and time packages. See the Go 1.15.4 milestone on our issue tracker for details.
1. go1.15.5 (released 2020/11/12) includes security fixes to the cmd/go and math/big packages. See the Go 1.15.5 milestone on our issue tracker for details.
See the [version notes](https://golang.org/doc/devel/release.html) for more release notes.
Verify the checksum …

Upgrades go version to 1.15.5

---

Dockerfile

This uses a base image that is Python 3.9 but _also_ node [14.5.1](https://github.com/CircleCI-Public/circleci-dockerfiles/blob/master/python/images/3.9.0-buster/node/Dockerfile#L21) (the latest LTS). I _think_ we need this as a bunch of our pre-commits are failing [here](https://github.com/transcom/transcom-infrasec-gov/pull/174) and [here](https://github.com/transcom/transcom-infrasec-com/pull/1288) and a plethora of others...So this puts node in the container, which should allow us to do do a `npm install` in CircleCI, which will hopefully satisfy pre-commit and allow tests to run, pass, and us ship code. This is largely a test...but I need to merge this to build/publish/tag a docker container. So here's a PR that does that.

No Ticket | We Need Node

---

Dockerfile

Updates to latest to match local home brew. Does _not_ upgrade Chamber to 2.9.0 per recommendation on Chamber's release page.
for clarity).

updates these to match local brew

---

.github/PULL_REQUEST_TEMPLATE.md
.pre-commit-config.yaml
milmove-app/Dockerfile

The ecs-service-logs script has been pulled out into its own repo. This PR adds the binary to the app image because it's required to deploy via circleci.
- [ecs-service-logs v3.0](https://github.com/trussworks/ecs-service-logs/releases/tag/v0.3.0)

Add upstream ecs-service-logs image to the app image

---

.circleci/config.yml
.dependabot/config.yml
README.md
build
milmove-infra-tf13/Dockerfile
scripts/find-updates
test

This creates a copy of the milmove-infra Docker image that can be used to allow a sidecar upgrade to Terraform 0.13. This makes it so we can leave everything as it exists for code that expects Terraform 0.12, but for code that expects Terraform 0.13, we can point to this image. Once the Terraform 0.13 upgrade is complete, this image can be deleted and its contents can be moved over to the milmove-infra image.
for clarity).
- …

add a new infra image for upgrading to terraform 0.13

---

milmove-infra/Dockerfile

Reverted #76 which I did this morning. Tried to go to 0.30.0 but got shasum mismatch so just reverted it rather than playing whack a mole with tfsec versions. I know 0.27.0 works.

reverts a part of #76

---

milmove-app/Dockerfile
milmove-orders/Dockerfile

Update go from 1.15.5 to 1.15.8. Includes release with security fixes.
Following instructions from https://github.com/transcom/mymove/wiki/upgrade-go-version
1. [golang](https://golang.org/doc/devel/release.html)
1. go1.15.6 (released 2020/12/03) includes fixes to the compiler, linker, runtime, the go command, and the io package. See the Go 1.15.6 milestone on our issue tracker for details.
1. go1.15.7 (released 2021/01/19) includes security fixes to the go command and the crypto/elliptic package. See the Go 1.15.7 milestone on our issue tracker for details.
1. go1.15.8 (released 2021/02/04) includes fixes to the compiler, linker, runtime, the go command, and the net/http package. See the Go 1.15.8 milestone on our issue tracker for details.

MB-6644 Update go version to 1.15.8

---

milmove-cypress/package.json

As of https://github.com/transcom/mymove/pull/5879 we are replacing Moment.js with another date library. The Cypress image in this repo had Moment listed as a dependency, but we were not actually using Moment in any Cypress code, so I am deleting it outright.

[MB-6392] Remove moment from Cypress dependencies

---

.github/dependabot.yml

This PR adjusts dependabot from checking for updates on a weekly basis to a daily basis (which matches the milmove dependabot config).  With them out of sync, we for instance get PRs about new cypress releases in milmove up to a week before getting the PRs here.
Some context here:
https://ustcdp3.slack.com/archives/CP6PTUPQF/p1611071982070600
Any reason we should leave it at weekly?

Adjust dependabot checks from weekly to daily

---

milmove-infra-tf13/Dockerfile
milmove-infra/Dockerfile

Pull in the updates from the infra-tf13 image so that the primary infra image is also on terraform 0.13.

MB-6744: bump primary infra image to tf 0.13

---

milmove-app/Dockerfile

New security patches to go. Upgrading docker image in prep to upgrade MilMove.

Upgrade to latest patch release of go 1.15.10

---

.circleci/config.yml
.github/dependabot.yml
README.md
build
milmove-infra-tf14/Dockerfile
scripts/find-updates
test

The main infra image uses Terraform 0.13. This PR converts the distinct Terraform 0.13 image to a Terraform 0.14 image, which can be used during the process of upgrading other repositories to use Terraform 0.14.
This also upgrades terrafrom-docs and tfsec to the latest available versions.

MB-6495: convert the terraform 0.13 image to a 0.14 image

---

.gitignore
Dockerfile
milmove-cypress/yarn.lock
milmove-infra-tf14/Dockerfile
milmove-infra/Dockerfile
requirements.txt
scripts/brew-upgrade

In addition to updating things, addresses low-severity CVE on `yarn.lock` and sets `0.14.9` as `tfenv use` rather than `0.13.6` in `scripts/brew-upgrade`.
This does successfully build locally, but given the changes to cypress docker file, may need someone from app-eng to take a look and/or verify things are working as expected.
for clarity).

[No Ticket] Updates things

---

milmove-cypress/package.json
milmove-cypress/yarn.lock

Update Cypress to 7.1 for `milmove-cypress`
for clarity).
- [cypress](https://www.cypress.io/)
- [ecs-service-logs](https://github.com/trussworks/ecs-service-logs/releases)
- [Google Chrome](https://chromereleases.googleblog.com/)
- [shellcheck](https://github.com/koalaman/shellcheck/releases)
- …

Update cypress to 7.1

---

milmove-app/Dockerfile

Update go from 1.15.10 to 1.16.4 in our docker images in anticipation of switching to Go 1.16.x in milmove.  This includes security fixes released in 1.16.4/1.15.12.
JIRA story: https://dp3.atlassian.net/browse/MB-8087
Go 1.16 release notes:
https://golang.org/doc/go1.16
Go 1.16.x version history:
https://golang.org/doc/devel/release.html#go1.16

[MB-8087] Update go version to 1.16.4

---

.github/PULL_REQUEST_TEMPLATE.md
milmove-atlantis/Dockerfile

Upgrades Atlantis so it can run on TF 15 in `transcom-gov-milmove-exp`
for clarity).
- [terraform](https://github.com/hashicorp/terraform/releases) (indirectly)

MB-8096: Upgrade Atlantis for exp

---

milmove-atlantis/Dockerfile

Removes default version env var as it's not necessary for us right now (also 0.15.3 is still latest...). 
I mistakenly thought this was needed to build. This takes it out and makes our code cleaner. 🧹

Upgrade Atlantis

---

milmove-infra-tf15/Dockerfile

Bump terraform-docs version to the latest version (v0.14.1).

bump terraform docs version

---

milmove-app/Dockerfile

Update go from 1.16.4 to 1.16.5 in our docker images in anticipation of switching to Go 1.16.5 in milmove. This includes security fixes released in 1.16.5.
To verify that go 1.16.5 is in the container, do the following:
1. `docker pull milmove/circleci-docker:milmove-app-12e26fdb58826aaa595111fd3793c2c00c1abda9` (to pull down the image -- that hash matches the commit hash in this PR)
1. While in the interactive shell, do a `go version` and verify that it says `1.16.5`
Go 1.16.x version history:
https://golang.org/doc/devel/release.html#go1.16

Upgrade golang to 1.16.5

---

milmove-app/Dockerfile

go-swagger 0.24.0 has a bug relating to readOnly parameter validations that has been fixed, so we'd like to update it.
We may have to make code changes in milmove before using this version of the container.
- [go-swagger](https://github.com/go-swagger/go-swagger/releases)

[MB-8383] Update go-swagger from 0.24.0 to 0.27.0

---

milmove-atlantis/Dockerfile

Update atlantis base image in dockerfile to version that supports terraform 1.0

[MB-8517] update atlantis base image to 0.17.2 for tf1 upgrade

---

milmove-infra-tf103/Dockerfile

rolls back tfsec to v39.29 from tfsec v50.7. 
Between these two versions, there are a lot of differences and added checks. a ticket has been made to update tfsec and fix the broken rules at a later date. 
for clarity).
- [tfsec](https://github.com/tfsec/tfsec/releases/tag/v0.39.29)

rollback tfsec

---

milmove-app/Dockerfile

Update go from 1.16.5 to 1.16.6 in our docker images in anticipation of switching to Go 1.16.6 in milmove. This includes security fixes released in 1.16.6.
To verify that go 1.16.6 is in the container, do the following:
1. `docker pull milmove/circleci-docker:milmove-app-d70c4d3c4457884822f04aca2d0278d8788a5db3` (to pull down the image -- that hash matches the commit hash in this PR)
1. While in the interactive shell, do a `go version` and verify that it says `1.16.6`
Go 1.16.x version history:
https://golang.org/doc/devel/release.html#go1.16

[MB-8828] Upgrade golang to 1.16.6

---

milmove-app/Dockerfile

Set go to 1.16.7

---

milmove-app/Dockerfile

Upgrade to go-1.7.1
for clarity).
- [golang](https://golang.org/doc/go1.17)

Upgrade to go-1.17.1

---

milmove-infra-tf104/Dockerfile

Bump terraform-docs and tfsec to the latest available versions.

bump terraform-docs and tfsec

---

milmove-app/Dockerfile

This PR upgrades the version of go-swagger that appears inside of the Docker image from version 0.27.0 to version 0.28.0.
- [go-swagger 0.28.0 release notes](https://github.com/go-swagger/go-swagger/releases/tag/v0.28.0)

Upgrade to go-swagger 0.28.0

---

milmove-cypress/package.json
milmove-cypress/yarn.lock

There is an issue in version 8.6.0 of cypress that carries into 9.2.1
which is causing the build to fail. Below is a link to the report of the
issue. Rolling back until the bug is fixed or time can be invested to
update the tests to avoid the issue.
https://github.com/cypress-io/cypress/issues/18464
for clarity).
- [cypress](https://www.cypress.io/)

MB-10966 Roll back to Cypress 8.5.0

---

.github/workflows/tfsec.yml
.gitignore

This PR adds a GitHub action to check for updates to tfsec every morning at 8AM. If there is a new release available, the workflow will automatically create a PR such as this one: https://github.com/transcom/circleci-docker/pull/200
I've left the tfsec version not updated so that we can test that the workflow happens at 4:40PM today.
* Add `shafile` to the gitignore because I don't want that coming into our repo when we curl it in the action
for clarity).
- …

[MB-11440] tfsec updater

---

.gitignore
milmove-app/Dockerfile

This PR upgrades the version of go-swagger that appears inside of the Docker image from version 0.28.0 to version 0.29.0.
I also added the folder used by JetBrains IDEs to the `.gitignore` file.
- [go-swagger 0.29.0 release notes](https://github.com/go-swagger/go-swagger/releases/tag/v0.29.0)

[MB-11565] Upgrade to go-swagger 0.29.0

---

milmove-app/Dockerfile

Update go from 1.17.5 to 1.17.7 in our docker images in anticipation of switching to Go 1.17.7 in milmove. This includes security fixes released in 1.17.7.
To verify that go 1.17.7 is in the container, do the following:
1. `docker pull milmove/circleci-docker:milmove-app-a944f0e14ba45fa65207b897b969e77840ed927b` (to pull down the image -- that hash matches the commit hash in this PR)
1. While in the interactive shell, do a `go version` and verify that it says `1.17.7`
Go 1.17.x version history:
https://golang.org/doc/devel/release.html#go1.17
I plan to test …

[MB-11847] Upgrade golang to 1.17.7

---

.github/PULL_REQUEST_TEMPLATE.md
README.md
milmove-app/Dockerfile

Update go from 1.17.7 to 1.18 in our docker images in anticipation of switching to Go 1.18 in milmove.
To verify that go 1.18 is in the container, do the following:
1. `docker pull milmove/circleci-docker:milmove-app-64b1fa9ea8c2c7ed8d5773829c142c30190bc2fb` (to pull down the image -- that hash matches the commit hash in this PR)
1. While in the interactive shell, do a `go version` and verify that it says `1.18`
Go 1.18.x version history:
https://go.dev/doc/devel/release#go1.18
Go 1.18 detailed release notes:
https://go.dev/doc/go1.18
I plan to test the …

[MB-11991] Update golang to 1.18

---

milmove-app/Dockerfile

Updates go to 1.18.1 for milmove-app. Using the method described here: https://transcom.github.io/mymove-docs/docs/backend/guides/how-to/upgrade-go-version . 
for clarity).

Update go version to 1.18.1 in milmove-app dockerfile

---

milmove-atlantis/Dockerfile

We may need to revert if this doesn't work. Trying to fix an issue with atlantis that resulted from this vulnerability being discovered: https://github.blog/2022-04-12-git-security-vulnerability-announced/

[MB-12078] add safe directory for all com modules

---

milmove-atlantis/Dockerfile

According to this troubleshooting post around Ansible, the environment
variable works similarly to the suggestion of using `git config` and is
recommended when using Docker. So let's try that and see if this helps.
[=> What to do when Git reports Fatal: Unsafe Repository](https://communities.sas.com/t5/SAS-Communities-Library/What-to-do-when-Git-reports-Fatal-Unsafe-Repository/ta-p/808910)
This could possibly unstuck transcom/transcom-infrasec-com#1944

Attempting to set GIT_CEILING_DIRECTORIES

---

milmove-app/Dockerfile

Update go from 1.18.1 to 1.18.4 Includes release with security fixes.
- go1.18.2 (released 2022-05-10) includes security fixes to the syscall package, as well as bug fixes to the compiler, runtime, the go command, and the crypto/x509, go/types, net/http/httptest, reflect, and sync/atomic packages. See the [Go 1.18.2 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.18.2+label%3ACherryPickApproved) on our issue tracker for details.
- go1.18.3 (released 2022-06-01) includes security fixes to the crypto/rand, crypto/tls, os/exec, and path/filepath packages, as well as bug fixes to the compiler, and the crypto/tls and text/template/parse packages. See the [Go 1.18.3 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.18.3 …

MB-13121 Update go version to 1.18.4 for milmove-app/Dockerfile

---

milmove-infra-tf112/Dockerfile

the automatic updater won't run on circleci and I haven't been able to figure it out :/

update tfsec to version 1.26.3

---

.circleci/config.yml
README.md

- updates the build file
- updates documentation that was still referencing master, including the status badge.
for clarity).
- [cypress](https://www.cypress.io/)
- [ecs-service-logs](https://github.com/trussworks/ecs-service-logs/releases)
- [Google …

NT: Missed 2 spots for the master=> main rename

---

milmove-app/Dockerfile

This PR upgrades the version of go-swagger that appears inside of the Docker image from version 0.29.0 to version 0.30.2.
- [go-swagger 0.30.2 release notes](https://github.com/go-swagger/go-swagger/releases/tag/v0.30.2)
- [go-swagger 0.30.0 release notes](https://github.com/go-swagger/go-swagger/releases/tag/v0.30.0)

[MB-13881] Upgrade go-swagger to version 0.30.2

---

milmove-app/Dockerfile

Update go from 1.18.4 to 1.19.1. 
Following instructions from [https://github.com/transcom/mymove/wiki/upgrade-go-version](https://github.com/transcom/mymove/wiki/upgrade-go-version)
- go1.18.5 (released 2022-08-01) includes security fixes to the encoding/gob and math/big packages, as well as bug fixes to the compiler, the go command, the runtime, and the testing package. See the [Go 1.18.5 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.18.5+label%3ACherryPickApproved) on our issue tracker for details.
- go1.18.6 (released 2022-09-06) includes security fixes to the net/http package, as well as bug fixes to the compiler, the go command, the pprof command, the runtime, and the crypto/tls, encoding/xml, and net packages. See the …

MB-13870: Update go version to 1.19.1

---

Dockerfile

The last couple of pull requests have failed to build due to [this error](https://app.circleci.com/pipelines/github/transcom/circleci-docker/921/workflows/87f8483e-7ee4-4708-bb85-f417eb3e61d6/jobs/984):
```
+ : Install apt packages
+ apt-get -qq -y install --no-install-recommends apt-transport-https groff less lsb-release
E: Failed to fetch http://deb.debian.org/debian/pool/main/d/distro-info-data/distro-info-data_0.41+deb10u4_all.deb  404  Not Found [IP: 146.75.34.132 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c set -ex && cd ~   && : Install apt packages   && apt-get -qq -y install --no-install-recommends apt-transport-https groff less lsb-release   && : Cleanup   && apt-get clean   && rm -vrf /var/lib/apt/lists/*' …
```

Add "apt-get update" to avoid fetch error

---

.github/PULL_REQUEST_TEMPLATE.md
README.md
milmove-app/Dockerfile
test

This PR removes [go-swagger](https://github.com/go-swagger/go-swagger) from the docker container.  This is a companion to [this ticket](https://github.com/transcom/mymove/pull/9352) on the MilMove side which is attempting to use a `go-swagger` that is managed via go as opposed to pre-installed in the docker container.  We've been having some issues with people [running differently-sourced/compiled versions](https://ustcdp3.slack.com/archives/CP6PTUPQF/p1663192043851619).
Don't merge this PR until we are sure that everything seems to be working on the MilMove side.  Once it's merged, then I'll update the hashes on the MilMove PR before merging it.

[MB-14038] Remove go-swagger from milmove app docker image

---

milmove-app/Dockerfile

Updates go from 1.19.1 to 1.19.2. Includes release with security fixes.
Following instructions from https://transcom.github.io/mymove-docs/docs/backend/guides/how-to/upgrade-go-version/
- go1.19.2 (released 2022-10-04) includes security fixes to the `archive/tar`, `net/http/httputil`, and `regexp` packages, as well as bug fixes to the compiler, the linker, the runtime, and the go/types package.

MB-14310: Updates Go version to 1.19.2

---

milmove-app/Dockerfile

Update go from 1.19.2 to 1.19.3 in our docker images in anticipation of switching to Go 1.19.3 in milmove.
To verify that go 1.19.3 is in the container, do the following:
1. `docker pull milmove/circleci-docker:milmove-app-50574f57827a7977149b68f02d497c47e062d472` (to pull down the image -- that hash matches the commit hash in this PR)
1. While in the interactive shell, do a `go version` and verify that it says `1.19.3`
I generally followed [these upgrade instructions](https://transcom.github.io/mymove-docs/docs/backend/guides/how-to/upgrade-go-version).
Go …

[MB-14371] Update golang to 1.19.3

---

milmove-cypress/package.json
milmove-cypress/yarn.lock

At several points we have upgraded Cypress in this image to a later version without making the corresponding change in MilMove.  We realized the mistake and changed MilMove to refer to an older hash from April 15, 2022 (with Cypress 8.5.0), but we didn't revert back to 8.5.0 in the `main` branch.  That makes it challenging to update other dependencies in `milmove-cypress` to a `main` hash since we'd accidentally be picking up the new Cypress version.  This PR rolls us back to Cypress 8.5.0 in the image to get in sync with MilMove's current state.

[MB-14464] Downgrade Cypress to 8.5.0 to sync up with current MilMove state

---

milmove-infra-tf132/Dockerfile

Rolling back tfsec to [1.28.0](https://github.com/aquasecurity/tfsec/releases/tag/v1.28.0) due to [bug](https://github.com/aquasecurity/tfsec/issues/1936)
for clarity).

Rollback tfsec to 1.28.0

---

.circleci/config.yml
README.md

This came out of the work involved in #339. This patch is only here to update
and re-enforce the work that already exists in the CircleCI build script today.
Essentially, the workflow is called `build-containers` and calls the job `build`
and filters on branches named after the checks in the current Build step named
_Check for reserved branch names_. While this check is useful on it's own to be
informative for developers, the check in the workflow does at least two things
well.
- Informs developers that their PR cannot and will not be merged in due to the
`build` job never running.
- Informs developers / operators of features for CI/CD that help perform
filtering and pattern matching for CircleCI.

[ spike ] Add a workflow for building containers

---

Dockerfile

We have been using `circleci/python:3.10.1-buster-node` as the base image for our various circleci-docker images (milmove-cypress, milmove-app, etc.).  However, I recently noticed the following:
- We used to get [dependabot updates](https://github.com/transcom/circleci-docker/pulls?q=buster-node) for this base image, but we haven't gotten one in over a year.
- It appears that the docker repository changed from [circleci/python](https://hub.docker.com/r/circleci/python) to [cimg/python](https://hub.docker.com/r/cimg/python) a while back, so dependabot hasn't been aware of any updates from the new repository ([more detail here](https://circleci.com/docs/next-gen-migration-guide/)).
- I also don't see the `buster` variant in the new repo (I believe that's referring to Debian 10). The …

[MB-15041, MB-15155] Updating deprecated docker repository reference and base image version

---

.github/CODEOWNERS

The platform team historically tends to be slow to respond to pull requests on this repository since we don't have codeowners configured. I added us as codeowners for the base docker image and the 3 subdirectories for specifically platform related images

[MB-15155] adds a codeowners file with platform team review

---

.pre-commit-config.yaml

Adding the `pre-commit` CircleCI job. This is part of my pre-vacation spikes to
help with developer experience on the project.

[ spike ] Adding the pre-commit CirlceCI task

---

.circleci/config.yml
release

This refactor is going to come in handy much later. But for now the refactor is focusing on not repeating ourselves similar to the `test-branch-name` where it iterates on the folders in the repository while reserving the `latest` word for the base or root `Dockerfile`.
Inspired by the work suggested in #339 between @ahobson and @rogeruiz.
This work will be further built on in future patches. I'll update this section once those PRs are created. This whole idea will hopefully replace the need for #339 to exist at all.

[ spike, MB-14548, MB-13732 ] Refactor the release script

---

milmove-app/Dockerfile

Update go from 1.19.3 to 1.20.1 in our docker images in anticipation of switching to Go 1.20.1 in milmove (see the [corresponding milmove PR](https://github.com/transcom/mymove/pull/10169)).  This new version incorporates some security fixes as well as opens the door for possible options related to FIPS 140-2 compliance.
To verify that go 1.20.1 is in the container, do the following:
```docker run --rm milmove/circleci-docker:milmove-app-b0321830e60511e17258e2d29abbc0dd8cf95d81 go version```
I generally followed [these upgrade instructions](https://transcom.github.io/mymove-docs/docs/backend/guides/how-to/upgrade-go-version).
Go 1.20.x version history:
https://go.dev/doc/devel/release#go1.20
Go 1.19.x version history:
https://go.dev/doc/devel/release#go1.19
I plan to test the milmove PR …

[MB-15297] Upgrade to go 1.20.1

---

Dockerfile

Reverts transcom/circleci-docker#377
See this [Slack thread](https://ustcdp3.slack.com/archives/CP4U2NKRT/p1677774846308069?thread_ts=1677706828.317889&cid=CP4U2NKRT) for more context.
In a nutshell, we get consistent failures in a couple of app deployment steps when using a `milmove-app` image that uses this updated base image that was merged last week in #377.  It only became apparent once I updated the `milmove-app` image to a new go version and used that hash (which includes the new base image) in milmove.  Based on tests on experimental (see the Slack thread above), going back to the previous version seems to clear up the problem.
[Here's the PR](https://github.com/transcom/mymove/pull/10185) on the MilMove side that references the hash for this PR's commit.  Once this is merged, …

[MB-15297] Revert "Bump cimg/python from 3.10.7-node to 3.11.2-node"

---

milmove-app/Dockerfile

Update go from 1.20.1 to 1.20.3 - Includes releases with security fixes.
[Followed this guide for upgrading](https://transcom.github.io/mymove-docs/docs/backend/guides/how-to/upgrade-go-version/)
[mymove update](https://github.com/transcom/mymove/pull/10450) that is currently in draft
- go1.20.2 (released 2023-03-07) includes a security fix to the crypto/elliptic package, as well as bug fixes to the compiler, the covdata command, the linker, the runtime, and the crypto/ecdh, crypto/rsa, crypto/x509, os, and syscall packages. See the [Go 1.20.2 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.20.2+label%3ACherryPickApproved) on our issue tracker for details.
- go1.20.3 (released 2023-04-04) includes security fixes to the …

[MB-15587] Upgrade to go 1.20.3

---

milmove-app/Dockerfile

[B-20641](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-20641)
- Upgrade Go 1.22.2 to 1.23.0
- Switch from [nodesource](https://deb.nodesource.com/) binary distribution to self-installed [nodejs distribution package](https://nodejs.org/dist/)
- This was done due to the nodesource script's sha256 no longer matching what we stored, with no release notes or tracking
Following instructions - here:
https://dp3.atlassian.net/wiki/spaces/MT/pages/1931673649/How+to+Upgrade+Go+Version
https://go.dev/doc/devel/release#go1.23.0

Go upgrade - 1.23.0
